# Shell padrão
shell /usr/bin/fish

# Permitir controle remoto (scripts, etc)
allow_remote_control yes

# Remove decorações da janela (barra de título, etc)
hide_window_decorations no

# Transparência e desfoque do fundo
background_opacity 0.7
background_blur 64

# Padding interno (dentro da janela)
window_padding_width 1

# Margens externas
window_margin_width_left 10
window_margin_width_right 10
window_margin_width_top 10
window_margin_width_bottom 10

# Fonte
font_family MesloLGMDZ Nerd Font
font_size 11
